# Generated by Django 2.2.1 on 2019-05-15 18:31

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('first_name', models.CharField(max_length=64, verbose_name='First name')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_1', models.CharField(max_length=255, verbose_name='Line 1')),
                ('line_2', models.CharField(max_length=255, verbose_name='Line 2')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=16, region=None, verbose_name='Phone number')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='person.Person')),
            ],
        ),
    ]
